### ISSUE TITLE
Estas utilizando una marca de linea de comandos no admitida: --no sandbox

### ISSUE THREAD

**Issue by richkidpe** [JijaProGamer/Youtube-View-Bot#14]
thanks for sharing but how do i fix this

**Comment by richkidpe** [comment]
![ss](https://github.com/JijaProGamer/Youtube-View-Bot/assets/143129152/d20de844-b5e1-4776-aa70-57c5b808ca4d)

**Comment by JijaProGamer** [comment]
Not a bug. Thats a intended feature by chromium.

**Comment by rdyvptnm** [comment]
@richkidpe i saw you are using gflow repo. i was wondering if we can connect and improve some features

**Comment by richkidpe** [comment]
solution bro?

**Comment by rdyvptnm** [comment]
Wanted to touch base on gflow project Sent from my iPhoneOn Sep 1, 2023, at 5:30 PM, richkidpe ***@***.***> wrote:﻿
solution bro?
