### ISSUE TITLE
I get this error when I try to log in with an account without a cookie

### ISSUE THREAD

**Issue by Cloudstrifeff7** [JijaProGamer/Youtube-View-Bot#28]
I get this error when I try to log in with an account without a cookie.

INFO: Error logging into google: Error: browserContext.addCookies: Cookie should have a valid expires, only -1 or a positive number for the unix timestamp in seconds is allowed

So the browser window opens, doesn't write anything to log in, and then closes.

Then in the cookie field I write, for example, -1. So the bot tries to log in but it freezes like that.

![image](https://github.com/JijaProGamer/Youtube-View-Bot/assets/5221033/a25daecd-8163-4968-950a-8ce38a6c2ef2)

![image](https://github.com/JijaProGamer/Youtube-View-Bot/assets/5221033/a4e2ba8e-1e40-4394-9b6f-fee8ed0c7d86)

Of course, I also get this error with different accounts that I have. However, if I try to start the bot without an account and try to log in it works.
I would like to try using cookies directly but I don't know how to extract them from the browser to make them compatible for the bot.

**Comment by JijaProGamer** [comment]
You need to leave cookies empty, not "-1".  Leaving "-1" will make the bot belive you did actually input some cookies, and fails to parse them.
