### ISSUE TITLE
Proxy check error

### ISSUE THREAD

**Issue by arshakags** [JijaProGamer/Youtube-View-Bot#5]
When i placed proxy then check all proxy error.i used private proxybfrom webshare.Please fix it

**Comment by JijaProGamer** [comment]
Did you add the correct proxy protocol before each proxy?

**Comment by arshakags** [comment]
Yeah i used format ip:port:user:pass

**Comment by arshakags** [comment]
Can you give me any screenshot for fill proxy?

**Comment by JijaProGamer** [comment]
Which protocol did you use, socks5:// or http:// ?

**Comment by JijaProGamer** [comment]
You need protocol://ip:port:user:pass

**Comment by arshakags** [comment]
Myproxy is https bro..i tired https://ip:port:user:pass still same error

**Comment by JijaProGamer** [comment]
It seems like webshare only has http and socks5 proxies?

**Comment by arshakags** [comment]
Yeah webshare http/https and socks5 proxy support

**Comment by JijaProGamer** [comment]
Try it with http instead of https

**Comment by arshakags** [comment]
I have tried with http or https but still same error bro if i skip for test proxy,url not loaded

**Comment by JijaProGamer** [comment]
Are you sure the proxy is working fine? Also does it say invalid URL or proxy too slow/timeout?

**Comment by arshakags** [comment]
My proxy working as well bro,they say invalid url bro

**Comment by JijaProGamer** [comment]
Can you send me your options.yaml file on my discord in a DM? I am Bloxxy213#8826

**Comment by arshakags** [comment]
Ok bro
