### ISSUE TITLE
number of views

### ISSUE THREAD

**Issue by mishav78** [JijaProGamer/Youtube-View-Bot#7]
1. If you use residential proxies can you get a million views ( I'm not trying to be funny) or is there some limit where YouTube says a million non logged in views is suspicious? 2. What actions do they take with suspicious behavior? 3. You can do 200 threads concurrently does that mean 200 open browser windows concurrently?

**Comment by JijaProGamer** [comment]
200 concurrency means that it opens 200 browsers. Unless you have over 64GB Ram and a I9 13900k you won’t be able to handle 200 browsers.

youtube may remove some views if you try to generate one million views, but it will take weeks to generate one million views anyways.
