### ISSUE TITLE
residential proxies

### ISSUE THREAD

**Issue by mishav78** [JijaProGamer/Youtube-View-Bot#8]
i tried with residential proxies. They only count 200 views at most non logged in views and sometimes they drop most of those. It seems you need logged in accounts.

**Comment by JijaProGamer** [comment]
which proxy provider are you using? Or you on the dev branch? What are your settings?

**Comment by mishav78** [comment]
webshare, ten million plan, refreshes every 15 minutes

**Comment by JijaProGamer** [comment]
Are you on the dev branch? If not, you should try it and check if views apply on the dev branch.

**Comment by mishav78** [comment]
what is the dev branch?

**Comment by lnb2g** [comment]
> webshare, ten million plan, refreshes every 15 minutes

how much you paying that this?
